---
clusterName: talos
endpoint: https://192.168.64.16:6443
talosVersion: v1.8.1
kubernetesVersion: v1.31.2
allowSchedulingOnMasters: true
clusterPodNets:
  - 10.32.0.0/12
clusterSvcNets:
  - 10.200.0.0/22
patches:
  - |-
    - op: add
      path: /machine/install/extraKernelArgs
      value:
        - net.ifnames=0
    - op: add
      path: /cluster/network/cni
      value:
        name: none
    - op: add
      path: /cluster/inlineManifests
      value:
         - name: kube-system-namespace-podsecurity
           contents: |
             apiVersion: v1
             kind: Namespace
             metadata:
               name: kube-system
               labels:
                 pod-security.kubernetes.io/enforce: privileged
    - op: replace
      path: /machine/kubelet/extraMounts
      value:
        - destination: /opt/local-path-provisioner
          type: bind
          source: /opt/local-path-provisioner
          options:
            - bind
            - rshared
            - rw
nodes:
  - hostname: cm
    controlPlane: true
    ipAddress: 192.168.64.16
    installDisk: /dev/vda
    networkInterfaces:
      - interface: br0
        addresses:
          - 172.16.1.60/24
        bridge:
          stp:
            enabled: true
          interfaces:
              - eth0
        routes:
            - network: 0.0.0.0/0 # The route's network (destination).
              gateway: 172.16.1.254 # The route's gateway (if empty, creates link scope route).
              metric: 1024 # The optional metric for the route.
